# action.yml
name: 'TIL Auto-Format README'
inputs:
  description:
    description: 'Description text block featured at the top of your README.md'
    required: false
    default: ''
  markdown_links_footer:
    description: 'Footer text block, can be used for things like markdown links'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
