name: Build and Push 
on:
  push:
    branches:
      - master
jobs:
  build_and_push:
    name: Build and Push Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Docker Login
        run: |
          echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin;
      - name: Build, Tag and Push
        run: |
          TAG="cflynnus/github-action-til-autoformat-readme:latest"
          docker build . --file ./Dockerfile-source -t "$TAG";
          docker push "$TAG";
