name: Build and Push 
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Test
        uses: cedrickring/golang-action/go1.14@1.5.2
        with:
          args: go test ./... -coverprofile=coverage.txt -covermode=atomic -coverpkg=main
        env:
          GO111MODULE: on
          GOFLAGS: -mod=vendor
      - name: Upload Coverage to CodeCov
        run: curl -s https://codecov.io/bash | bash -s -- -t ${{secrets.CODECOV_TOKEN}} -f ./coverage.txt
  build_and_push:
    name: Build and Push Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Docker Login
        run: |
          echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin;
      - name: Build, Tag and Push
        run: |
          TAG="cflynnus/github-action-til-autoformat-readme:latest"
          docker build . --file ./Dockerfile-source -t "$TAG";
          docker push "$TAG";
